# Generated by Django 5.2.4 on 2025-08-25 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_appointment_service_type_appointment_therapist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('registration', 'Registration Verification'), ('password_reset', 'Password Reset'), ('email_change', 'Email Change Verification')], max_length=20)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('verification_code', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='clinic_emai_token_a4a7d1_idx'), models.Index(fields=['verification_code'], name='clinic_emai_verific_51f84d_idx'), models.Index(fields=['user', 'verification_type'], name='clinic_emai_user_id_269f9d_idx'), models.Index(fields=['expires_at'], name='clinic_emai_expires_198ba5_idx')],
            },
        ),
    ]
