# Generated by Django 5.2.4 on 2025-08-30 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_customuser_unique_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='guest_age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='appointment',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='guest_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='guest_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='guest_id',
            field=models.CharField(blank=True, help_text='Unique identifier for guest appointments', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='guest_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='True if this is a guest appointment'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['is_guest'], name='clinic_appo_is_gues_fdb8ba_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['guest_id'], name='clinic_appo_guest_i_208ae8_idx'),
        ),
    ]
