# Generated by Django 5.2.4 on 2025-07-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_patient_reason_for_treatment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
    ]
